# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'GiphyViewer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.0.0.beta.1'
  pod 'SwiftyGiphy', '~> 1.0'

  # Pods for GiphyViewer

end
